### ISSUE TITLE
Locales missing

### ISSUE THREAD

**Issue by nplezka** [categulario/full-battery-gnome-shell-extension#1]
Hi, I'm on Ubuntu 20.04 with italian locale.
I tried to modify your spanish locale in the italian one but it doesn't seem to work.
Maybe I'm forgetting something.
Just in case, these are the translated strings:

"Batteria completamente carica, disconnetti il caricatore."
"Batteria quasi carica: "

**Comment by categulario** [comment]
Hi! let me check that

**Comment by categulario** [comment]
did you change the language code at line 14 of the .po file? If you make a pull request I can check it out locally and fix whatever needs to be fixed (:

**Comment by nplezka** [comment]
I just checked and changing "it" to "it_IT" at the line 14 now it works fine! (: 
Oh, the locale folder (/locale/it/LC_MESSAGES) is named "it" instead.

I think I made the request but I think I made a mistake here in Github, let me see I can solve it.
I'm uploading the file here anyway:

[fullbattery.zip](https://github.com/categulario/full-battery-gnome-shell-extension/files/4396012/fullbattery.zip)

(:

**Comment by categulario** [comment]
I just saw your PR. Will be merged asap, just take a look at the comment I made.

Just because I'm curious, which version of gnome are you using?

**Comment by nplezka** [comment]
The latest 3.36 (maybe with some 3.34 left, Ubuntu 20.04 is still in development...)

**Comment by categulario** [comment]
motivated by your contribution I asked some friends to translate the messages to other languages:

https://github.com/categulario/full-battery-gnome-shell-extension/commit/220f4e8e2188e31e41406e897a729efba89296a2

**Comment by categulario** [comment]
I'll close this issue for now. If someone else finds that a language is missing they will hopefully open another issue. Thanks for your help, you made me the happiest programmer on earth just by using this extension (:
